apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: producing-log-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: producing-log
        version: v2
    spec:
      containers:
      - name: producing-log
        image: index.caicloud.io/caicloud/producing-log:1.0
